import { MajorityRound } from "../supabase";

// Either/or prompts. Players vote their pick AND predict the room's majority.
export const MAJORITY_BANK: MajorityRound[] = [
  { a: "Beach vacation", b: "Mountain cabin" },
  { a: "Pizza", b: "Tacos" },
  { a: "Ability to fly", b: "Ability to be invisible" },
  { a: "Dogs", b: "Cats" },
  { a: "Sweet snacks", b: "Salty snacks" },
  { a: "Movie at home", b: "Movie in theatre" },
  { a: "Summer", b: "Winter" },
  { a: "Coffee", b: "Tea" },
  { a: "Early bird", b: "Night owl" },
  { a: "Texting", b: "Calling" },
  { a: "Time travel to the past", b: "Time travel to the future" },
  { a: "Live without music", b: "Live without TV" },
  { a: "Always slightly too hot", b: "Always slightly too cold" },
  { a: "Read minds", b: "See the future" },
  { a: "Burgers", b: "Hot dogs" },
  { a: "Pancakes", b: "Waffles" },
  { a: "Window seat", b: "Aisle seat" },
  { a: "Camping in a tent", b: "Fancy hotel" },
  { a: "Never wait in line again", b: "Never hit a red light again" },
  { a: "Breakfast for dinner", b: "Dinner for breakfast" },
  { a: "Lose your phone for a week", b: "Lose your car for a week" },
  { a: "Sing every sentence", b: "Rhyme every sentence" },
  { a: "Fries", b: "Onion rings" },
  { a: "Chocolate", b: "Chips" },
  { a: "One 3-week vacation", b: "Three 1-week vacations" },
  { a: "Rewatch old favourites", b: "Only watch new stuff" },
  { a: "Cook every meal forever", b: "Order in every meal forever" },
  { a: "Talk to animals", b: "Speak every language" },
  { a: "Free flights for life", b: "Free food for life" },
  { a: "Live by the ocean", b: "Live by a lake" },
  { a: "Always 10 minutes early", b: "Always exactly on time" },
  { a: "Karaoke in front of strangers", b: "Karaoke in front of coworkers" },
  { a: "Ice cream", b: "Cake" },
  { a: "Pool", b: "Hot tub" },
  { a: "Board games", b: "Video games" },
  { a: "New Year's Eve party", b: "Quiet New Year's at home" },
  { a: "Be the funniest person in the room", b: "Be the smartest person in the room" },
  { a: "Only whisper forever", b: "Only shout forever" },
  { a: "Fight one horse-sized duck", b: "Fight 100 duck-sized horses" },
  { a: "No internet for a month", b: "No shower for a week" },
  { a: "Cereal before milk", b: "Milk before cereal" },
  { a: "Hawaiian pizza is great", b: "Pineapple doesn't belong on pizza" },
  { a: "Toilet paper over the roll", b: "Toilet paper under the roll" },
  { a: "Win $50k now", b: "50/50 shot at $500k" },
  { a: "Road trip", b: "Flight" },
  { a: "Spicy food", b: "Mild food" },
  { a: "Give up cheese forever", b: "Give up chocolate forever" },
  { a: "Know how you die", b: "Know when you die" },
  { a: "Redo high school", b: "Skip straight to retirement" },
  { a: "Famous but broke", b: "Rich but unknown" },
  { a: "Concert front row", b: "Sports game front row" },
  { a: "Real Christmas tree", b: "Artificial Christmas tree" },
  { a: "Shovel snow", b: "Rake leaves" },
  { a: "BBQ", b: "Buffet" },
  { a: "Always know the time without a clock", b: "Always know north without a compass" },
  { a: "Live in a treehouse", b: "Live in a houseboat" },
  { a: "Unlimited gas", b: "Unlimited groceries" },
  { a: "Be a movie star", b: "Be a rock star" },
  { a: "Silent disco", b: "Regular concert" },
  { a: "Wear socks with sandals forever", b: "Wear a winter hat all summer" },
  { a: "Mustard", b: "Ketchup" },
  { a: "Shark diving", b: "Skydiving" },
  { a: "Only leftovers forever", b: "Never leftovers again" },
  { a: "Lose all your photos", b: "Lose all your text history" },
];
