// Scale pairs for Vibe Check. Left = 0, right = 100.
export type Scale = { left: string; right: string };

export const VIBE_SCALES: Scale[] = [
  { left: "Hot", right: "Cold" },
  { left: "Overrated", right: "Underrated" },
  { left: "Scary", right: "Cozy" },
  { left: "Cheap", right: "Expensive" },
  { left: "Healthy", right: "Junk food" },
  { left: "Loud", right: "Quiet" },
  { left: "Guilty pleasure", right: "Openly proud" },
  { left: "Weekday", right: "Weekend" },
  { left: "Introvert", right: "Extrovert" },
  { left: "Fancy", right: "Casual" },
  { left: "Useless", right: "Essential" },
  { left: "Old school", right: "Cutting edge" },
  { left: "Kids' movie", right: "Adults' movie" },
  { left: "Snack", right: "Meal" },
  { left: "Sport", right: "Hobby" },
  { left: "Famous", right: "Obscure" },
  { left: "Morning person thing", right: "Night owl thing" },
  { left: "Beach vacation", right: "Mountain vacation" },
  { left: "Dog energy", right: "Cat energy" },
  { left: "Karaoke song", right: "Shower song" },
  { left: "Smells amazing", right: "Smells terrible" },
  { left: "Summer", right: "Winter" },
  { left: "Sweet", right: "Savoury" },
  { left: "Dangerous", right: "Safe" },
  { left: "Romantic", right: "Unromantic" },
  { left: "Normal", right: "Weird" },
  { left: "Soft", right: "Crunchy" },
  { left: "Underdressed", right: "Overdressed" },
  { left: "Small talk", right: "Deep talk" },
  { left: "First date food", right: "Third date food" },
  { left: "Superpower", right: "Curse" },
  { left: "Art", right: "Not art" },
  { left: "Worth waiting in line for", right: "Never worth the line" },
  { left: "Fun at 10", right: "Fun at 40" },
  { left: "Aged well", right: "Aged badly" },
  { left: "Sounds fake", right: "Sounds true" },
  { left: "Good gift", right: "Terrible gift" },
  { left: "Comfort food", right: "Special occasion food" },
  { left: "Easy to learn", right: "Hard to master" },
  { left: "Clean", right: "Messy" },
  { left: "Round", right: "Pointy" },
  { left: "Villain move", right: "Hero move" },
  { left: "Basic", right: "One of a kind" },
  { left: "Nature", right: "Technology" },
  { left: "Tastes better cold", right: "Tastes better hot" },
  { left: "Wedding song", right: "Gym song" },
  { left: "Board game night", right: "Big night out" },
  { left: "Trustworthy animal", right: "Sketchy animal" },
  { left: "Would survive an apocalypse", right: "Gone in a week" },
  { left: "Icon", right: "Flash in the pan" },
];
